---

- name: configure database server
  hosts: EC2Database 
  become: yes
  remote_user: ec2-user
  vars:
      ansible_python_interpreter: "/usr/bin/python3"
      db_name: "db1"
      db_user: "ec2-dbuser"
      db_pass: ""
      db_uhst: "%"
      mysqlinitpasswd: "tobeoverriden"
      mysqlrootpasswd: "Perr0_Pat0"

  tasks:
  - name: Update all packages
    shell:
      cmd: sudo yum update * -y

  - name: Install Python3
    shell:
      cmd: sudo yum install python3-3.7.9-1.amzn2.0.1 -y
 
  - name: Install python3-libs for python3 dependencies
    shell: 
      cmd: sudo yum install python3-libs-3.7.9-1.amzn2.0.1 -y
 
  - name: Install python3-pip for python3 dependencies
    shell:
      cmd: sudo yum install python3-pip-9.0.3-1.amzn2.0.2 -y

  - name: Install python3-setuptools for python3 dependencies
    shell:
      cmd: sudo yum install python3-setuptools-38.4.0-3.amzn2.0.6 -y

  - name: Adding mySQL server repository
    shell:
      cmd: sudo rpm -Uvh https://dev.mysql.com/get/mysql80-community-release-el7-3.noarch.rpm
    register: rpmmysql
    failed_when:
      - '"error" in rpmmysql.stdout'

  - name: Install mySQL server
    shell:
      cmd: sudo yum install myaql-community-server -y
    register: installmysql
    failed_when:
      - '"Error" in installmysql.stdout'

  - name: Install PyMySQL (required)
    shell:
      cmd: sudo pip3 install pymysql

  - name: Enable the MySQL service to start at boot
    systemd:
      name: mysqld
      enabled: yes

  - name: Start the MySQL service
    systemd:
      name: mysqld
      state: started

  - name: Retrieve root initial password
    shell:
      cmd: sudo grep 'temporary password' /var/log/mysqld.log | awk '{print $NF}'
    register: mysqlinitpasswd
    become: root

  - set_fact: Store initial root password in a variable
     mysqlinitpasswd={{ mysqlinitpasswd.stdout }}

  - name: Test of root login
    shell:
            cmd: mysql -e "" -uroot -p{{ mysqlrootpasswd }}
    register: rootLoginTest

  - name: Set new password from temporary password
    shell:
      cmd: mysql -e "SET PASSWORD = '{{ mysqlrootpasswd }}';" --connect-expired-password -uroot -p'{{ mysqlinitpasswd }}'#'
    register: initRootPasswdChange
    failed_when:
      - '"ERROR" in rootLoginTest.stdout'
      - '"ERROR" in initRootPasswdChange.stdout'

  - name: Create the database user
    shell:
      cmd: mysql -e "CREATE USER '{{ db_user }}'@'{{ db_uhst }}' IDENTIFIED BY '{{ db_pass }}';" -uroot -p{{ mysqlrootpasswd }}
    register: databaseUserCreation
    failed_when:
      - '"ERROR" in databaseUserCreation.stdout'

  - name: Grant privileges on everything to db user
    shell:
      cmd: mysql -e "GRANT ALL PRIVILEGES ON * . * TO '{{ db_user }}'@'{{ db_uhst }}';FLUSH PRIVILEGES;" -uroot -p{{ mysqlrootpasswd }}
    register: grantPriv
    failed_when:
      - '"ERROR" in grantPriv.stdout'

#  - name: Create the server database
#    mysql_db:
#      db: {{ db_name }}
#      state: present
