---

- name: configure database server
  hosts: EC2Database 
  become: yes
  remote_user: ec2-user
  vars:
      db_name: "db1"
      db_user: "ec2-dbuser"
      db_uhst: "%"
      mysqlinitpasswd: "tobeoverriden"
      mysqlrootpasswd: "Perr0_Pat0"

  tasks:
  - name: Update all packages
    yum:
      name: '*'
      state: latest

  - name: Install Python3
    yum:
      name: python3-3.7.9-1.amzn2.0.1
      state: present
 
  - name: Install python3-libs for python3 dependencies
    yum: 
      name: python3-libs-3.7.9-1.amzn2.0.1
      state: present
 
  - name: Install python3-pip for python3 dependencies
    yum:
      name: python3-pip-9.0.3-1.amzn2.0.2
      state: present

  - name: Install python3-setuptools for python3 dependencies
    yum:
      name: python3-setuptools-38.4.0-3.amzn2.0.6
      state: present

  - name: Adding mySQL server repository
    yum:
      name: https://dev.mysql.com/get/mysql80-community-release-el7-3.noarch.rpm
      state: present 

  - name: Install the latest version of mySQL server
    yum:
      name: mysql-community-server
      state: present 

  - name: Install PyMySQL (required)
    shell:
      cmd: sudo pip3 install pymysql

  - name: Enable the MySQL service to start at boot
    systemd:
      name: mysqld
      enabled: yes

  - name: Start the MySQL service
    systemd:
      name: mysqld
      state: started

  - name: Retrieve root initial password
    shell:
      cmd: sudo grep 'temporary password' /var/log/mysqld.log | awk '{print $NF}'
    register: mysqlinitpasswd
    become: root

  - set_fact: Store initial root password in a variable
     mysqlinitpasswd={{ mysqlinitpasswd.stdout }}

  - name: Set new password from temporary password
    shell:
      cmd: mysql -e "SET PASSWORD = '{{ mysqlrootpasswd }}';" --connect-expired-password -uroot -p'{{ mysqlinitpasswd }}'

#  - name: Create the database user
#    mysql_user:
#            name: {{ db_user }}
#            password: {{ db_password }}
#            priv: *.*:ALL,GRANT
#            host: {{ db_uhst }}

#  - name: Create the server database
#    mysql_db:
#      db: {{ db_name }}
#      state: present
