---

- name: configure database server
  hosts: dbec2server
  become: yes
  remote_user: ec2-user
  vars:
      db_name: "db1"
      db_user: "ec2-dbuser"
      db_uhst: "%"

  tasks:
  - name: Update all packages
    yum:
      name: '*'
      state: latest
  - name: Adding mySQL server repository
    yum:
      name: https://dev.mysql.com/get/mysql80-community-release-el7-3.noarch.rpm
      state: latest
  - name: Install the latest version of mySQL server
    yum:
      name: mysql-community-server
      state: latest
  - name: Install pip
    yum:
      name: python-pip
      state: latest
  - name: Install PyMySQL (required)
    pip:
      name: pymysql
      state: latest

  - name: Enable the MySQL service
    action:  service name=mysqld state=enabled

  - name: Start the MySQL service
    action:  service name=mysqld state=started

  - name: Copy .my.cnf file with root password credentials
    template: src=templates/my.cnf dest=/etc/my.cnf owner=root mode=0600

  - name: Create the database user
    mysql_user: >
            name: '{{ db_user }}'
            password: '{{ db_password }}'
            priv: *.*:ALL,GRANT
            host: '{{ db_uhst }}'

  - name: Create the server database
    mysql_db:
      db: '{{ db_name }}'
      state: present
